on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.0
          run_install: |
            - recursive: false
              args: [--frozen-lockfile, --strict-peer-dependencies]
          

      - name: Build project
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: pnpm run build

      - name: Publish to cloudflare pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: responsive-screenshots
          directory: "dist"
          gitHubToken: ${{secrets.GITHUB_TOKEN }}
